version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/nokamoto/grpc-proxy
    steps:
      - checkout
      - run:
          name: get prototool
          command: |
            curl -sSL https://github.com/uber/prototool/releases/download/v1.0.0/prototool-$(uname -s)-$(uname -m) -o ./prototool
            chmod +x ./prototool
      - run: ./prototool format -d examples
      - run:
          name: get protoc
          command: |
            curl -L https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip -o ./protoc.zip
            unzip ./protoc.zip -d .
      - run:
          working_directory: /go/src/github.com/nokamoto/grpc-proxy/examples/empty-package
          environment:
            PATH: /go/src/github.com/nokamoto/grpc-proxy:$PATH
          command: make
      - run:
          working_directory: /go/src/github.com/nokamoto/grpc-proxy/examples/ping
          environment:
            PATH: /go/src/github.com/nokamoto/grpc-proxy:$PATH
          command: make
      - run:
          name: go get dependencies
          command: |
            go get -u golang.org/x/lint/golint
            go get -u github.com/golang/dep/cmd/dep
      - run: test -z "$(gofmt -l .)"
      - run: golint -set_exit_status .
      - run: dep ensure -vendor-only=true
      - run: go test .
workflows:
  version: 2
  ci:
    jobs:
      - test
